In [1]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen3-4B-Base",
    max_seq_length = max_seq_length,
    load_in_4bit = False, # False for LoRA 16bit
    fast_inference = True, # Enable vLLM fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2, # *2 speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
#### Unsloth: `hf_xet==1.1.10` and `ipykernel>6.30.1` breaks progress bars. Disabling for now in XET.
#### Unsloth: To re-enable progress bars, please downgrade to `ipykernel==6.30.1` or wait for a fix to
https://github.com/huggingface/xet-core/issues/526
INFO 12-16 22:01:30 [__init__.py:225] Automatically detected platform rocm.
🦥 Unsloth Zoo will now patch everything to make training faster!
Unsloth: AMD currently is not stable with 4bit bitsandbytes. Disabling for now.

[2025-12-16 22:01:33] INFO vllm_utils.py:752: Unsloth: Patching vLLM

INFO 12-16 22:01:33 [vllm_utils.py:694] Unsloth: Patching vLLM v1 graph capture
Unsloth: Could not patch vLLM V0 graph capture: No module named 'vllm.worker'
==((====))==  Unsloth 2025.10.9: Fast Qwen3 patching. Transformers: 4.56.2. vLLM: 0.11.1rc3.dev39+gf417746ad.rocm700.
   \\   /|    . Num GPUs = 1. Max memory: 191.688 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0a0+git1c57644. ROCm Toolkit: 7.0.51831-a3e329ad8. Triton: 3.4.0
\        /    Bfloat16 = TRUE. FA [Xformers = None. FA2 = True]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: vLLM loading unsloth/Qwen3-4B-Base with actual GPU utilization = 89.84%
Unsloth: Your GPU has CUDA compute capability 9.4 with VRAM = 191.69 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 400.
Unsloth: vLLM's KV Cache can use up to 165.26 GB. Also swap space = 6 GB.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
INFO 12-16 22:01:34 [utils.py:253] non-default args: {'dtype': torch.bfloat16, 'seed': 0, 'max_model_len': 2048, 'enable_prefix_caching': True, 'swap_space': 6, 'gpu_memory_utilization': 0.8983952151940007, 'max_num_batched_tokens': 2048, 'max_num_seqs': 400, 'max_logprobs': 0, 'disable_log_stats': True, 'enable_lora': True, 'max_lora_rank': 32, 'enable_chunked_prefill': True, 'compilation_config': {'level': None, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'inductor', 'custom_ops': [], 'splitting_ops': None, 'use_inductor': None, 'compile_sizes': None, 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': None, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'full_cuda_graph': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': None, 'local_cache_dir': None}, 'model': 'unsloth/Qwen3-4B-Base'}
INFO 12-16 22:01:35 [model.py:667] Resolved architecture: Qwen3ForCausalLM
INFO 12-16 22:01:35 [model.py:1756] Using max model len 2048
INFO 12-16 22:01:36 [scheduler.py:219] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 12-16 22:01:36 [core.py:94] Initializing a V1 LLM engine (v0.11.1rc3.dev39+gf417746ad) with config: model='unsloth/Qwen3-4B-Base', speculative_config=None, tokenizer='unsloth/Qwen3-4B-Base', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=2048, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen3-4B-Base, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={'level': None, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention', 'vllm::sparse_attn_indexer'], 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'use_cudagraph': True, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], 'cudagraph_copy_inputs': False, 'full_cuda_graph': True, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_capture_size': 512, 'local_cache_dir': None}
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
INFO 12-16 22:01:36 [parallel_state.py:1325] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 12-16 22:01:36 [gpu_model_runner.py:2856] Starting to load model unsloth/Qwen3-4B-Base...
INFO 12-16 22:01:37 [rocm.py:304] Using Triton Attention backend on V1 engine.
INFO 12-16 22:01:37 [weight_utils.py:419] Using model weights format ['*.safetensors']

Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]

INFO 12-16 22:01:40 [default_loader.py:314] Loading weights took 2.79 seconds
INFO 12-16 22:01:40 [punica_selector.py:20] Using PunicaWrapperGPU.
INFO 12-16 22:01:40 [gpu_model_runner.py:2917] Model loading took 7.7168 GiB and 3.203181 seconds
INFO 12-16 22:01:47 [backends.py:609] Using cache directory: /root/.cache/vllm/torch_compile_cache/8fa1e2fba3/rank_0_0/backbone for vLLM's torch.compile
INFO 12-16 22:01:47 [backends.py:623] Dynamo bytecode transform time: 7.01 s
INFO 12-16 22:01:50 [backends.py:207] Directly load the compiled graph(s) for dynamic shape from the cache, took 1.876 s
INFO 12-16 22:02:04 [monitor.py:34] torch.compile takes 8.88 s in total
INFO 12-16 22:02:05 [gpu_worker.py:337] Available KV cache memory: 161.61 GiB
INFO 12-16 22:02:05 [kv_cache_utils.py:1229] GPU KV cache size: 1,176,800 tokens
INFO 12-16 22:02:05 [kv_cache_utils.py:1234] Maximum concurrency for 2,048 tokens per request: 574.61x
INFO 12-16 22:02:05 [vllm_utils.py:699] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE):   0%|                                                                             | 0/134 [00:00<?, ?it/s]

WARNING 12-16 22:02:05 [utils.py:222] Using default LoRA kernel configs

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|███████████████████████████████████████████████████████████████████| 134/134 [00:09<00:00, 13.53it/s]
Capturing CUDA graphs (decode, FULL): 100%|██████████████████████████████████████████████████████████████████████████████████████| 106/106 [00:08<00:00, 12.74it/s]

INFO 12-16 22:02:24 [gpu_model_runner.py:3843] Graph capturing finished in 18 secs, took 1.10 GiB
INFO 12-16 22:02:24 [vllm_utils.py:706] Unsloth: Patched vLLM v1 graph capture finished in 18 secs.

INFO 12-16 22:02:24 [core.py:238] init engine (profile, create kv cache, warmup model) took 43.98 seconds
INFO 12-16 22:02:25 [llm.py:343] Supported tasks: ('generate',)
Unsloth: Just some info: will skip parsing ['attention_norm', 'layer_norm2', 'k_norm', 'pre_feedforward_layernorm', 'q_norm', 'ffn_norm', 'input_layernorm', 'norm2', 'layer_norm1', 'post_layernorm', 'norm1', 'post_attention_layernorm', 'post_feedforward_layernorm']

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Unsloth: Just some info: will skip parsing ['attention_norm', 'layer_norm2', 'k_norm', 'pre_feedforward_layernorm', 'cross_attn_post_attention_layernorm', 'q_norm', 'ffn_norm', 'input_layernorm', 'cross_attn_input_layernorm', 'norm2', 'layer_norm1', 'post_layernorm', 'norm1', 'post_attention_layernorm', 'post_feedforward_layernorm']

Unsloth 2025.10.9 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

In [2]:
reasoning_start = "<start_working_out>" # Acts as <think>
reasoning_end   = "<end_working_out>"   # Acts as </think>
solution_start  = "<SOLUTION>"
solution_end    = "</SOLUTION>"

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
Place it between {reasoning_start} and {reasoning_end}.
Then, provide your solution between {solution_start}{solution_end}"""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION>'

In [3]:
chat_template = \
    "{% if messages[0]['role'] == 'system' %}"\
        "{{ messages[0]['content'] + eos_token }}"\
        "{% set loop_messages = messages[1:] %}"\
    "{% else %}"\
        "{{ '{system_prompt}' + eos_token }}"\
        "{% set loop_messages = messages %}"\
    "{% endif %}"\
    "{% for message in loop_messages %}"\
        "{% if message['role'] == 'user' %}"\
            "{{ message['content'] }}"\
        "{% elif message['role'] == 'assistant' %}"\
            "{{ message['content'] + eos_token }}"\
        "{% endif %}"\
    "{% endfor %}"\
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"\
    "{% endif %}"

# Replace with out specific template:
chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{system_prompt}'")\
    .replace("'{reasoning_start}'", f"'{reasoning_start}'")
tokenizer.chat_template = chat_template

In [4]:
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}{solution_start}2{solution_end}"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|endoftext|>What is 1+1?<start_working_out>I think it's 2.<end_working_out><SOLUTION>2</SOLUTION><|endoftext|>What is 2+2?<start_working_out>"

Pre fine-tuning for formatting
We now use a subset of NVIDIA's Open Math Reasoning dataset which was filtered to only include high quality DeepSeek R1 traces.

We'll only filter ~59 or so examples to first "prime" / pre fine-tune the model to understand our custom GRPO formatting.

In [5]:
from datasets import load_dataset
import pandas as pd
import numpy as np

dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.to_pandas()[
    ["expected_answer", "problem", "generated_solution"]
]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(dataset["expected_answer"]), errors = "coerce").notnull()
# Select only numbers
dataset = dataset.iloc[np.where(is_number)[0]]

dataset

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

In [6]:
def format_dataset(x):
    expected_answer = x["expected_answer"]
    problem = x["problem"]

    # Remove generated <think> and </think>
    thoughts = x["generated_solution"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")

    # Strip newlines on left and right
    thoughts = thoughts.strip()
    # Add our custom formatting
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
        solution_start + expected_answer + solution_end
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

dataset["Messages"] = dataset.apply(format_dataset, axis = 1)

In [7]:
tokenizer.apply_chat_template(dataset["Messages"][0], tokenize = False)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Given $\\sqrt{x^2+165}-\\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<start_working_out>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\nTo solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]<end_working_out><SOLUTION>14</SOLUTION><|endoftext|>"

In [8]:
dataset["N"] = dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))

dataset = dataset.loc[dataset["N"] <= max_seq_length/2].copy()
dataset.shape

(59, 5)

In [9]:
from datasets import Dataset

dataset["text"] = tokenizer.apply_chat_template(dataset["Messages"].values.tolist(), tokenize = False)
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'Messages', 'N', 'text', '__index_level_0__'],
    num_rows: 59
})

In [10]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 1, # Use GA to mimic batch size!
        warmup_steps = 5,
        num_train_epochs = 2, # Set this for 1 full training run.
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.001,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use TrackIO/WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=24):   0%|          | 0/59 [00:00<?, ? examples/s]

In [11]:
trainer.train()

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 151654}.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 59 | Num Epochs = 2 | Total steps = 118
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 1 x 1) = 1
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=118, training_loss=0.3524919717998828, metrics={'train_runtime': 46.1989, 'train_samples_per_second': 2.554, 'train_steps_per_second': 2.554, 'total_flos': 2374193075607552.0, 'train_loss': 0.3524919717998828, 'epoch': 2.0})

In [12]:
text = tokenizer.apply_chat_template(
    dataset[0]["Messages"][:2],
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer(text, return_tensors = "pt").to("cuda"),
    temperature = 0,
    max_new_tokens = 1024,
    streamer = TextStreamer(tokenizer, skip_prompt = False),
)

You are given a problem.
Think about the problem and provide your working out.
Place it between <start_working_out> and <end_working_out>.
Then, provide your solution between <SOLUTION></SOLUTION><|endoftext|>Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?<start_working_out>Okay, let's see. Jenifer has 82 cents in pennies and nickels. Her younger brother thought all the nickels were dimes and counted the total as $1.47. I need to find out how many pennies Jenifer has. Hmm, let's break this down.

First, I need to set up some equations. Let's say the number of pennies is P and the number of nickels is N. Since pennies are worth 1 cent and nickels are worth 5 cents, the total value Jenifer has is 1P + 5N = 82 cents. That's the first equation.

Now, her brother mistook all the nickels for dimes. Dimes are worth 10 cents. So, he counted the total as $1.47, which is 147 cents. So, the equation for his count would be 1P + 10N = 147. That's the second equation.

So now I have two equations:
1. P + 5N = 82
2. P + 10N = 147

I need to solve these two equations to find P. Let me think. Maybe I can subtract the first equation from the second to eliminate P. Let's try that.

Subtracting equation 1 from equation 2:
(P + 10N) - (P + 5N) = 147 - 82
Which simplifies to:
5N = 65
Then, dividing both sides by 5:
N = 13

So there are 13 nickels. Now, plug N back into the first equation to find P:
P + 5(13) = 82
P + 65 = 82
Subtract 65 from both sides:
P = 17

So Jenifer has 17 pennies. Let me check that. If she has 17 pennies and 13 nickels, that's 17 + 65 = 82 cents, which matches. Her brother would count the nickels as dimes, so 17 pennies and 13 dimes would be 17 + 130 = 147 cents, which is $1.47. That checks out. So the answer should be 17 pennies.
To solve the problem, we start by setting up two equations based on the given information.

1. Jenifer has 82 cents in pennies and nickels. Let \( P \) be the number of pennies and \( N \) be the number of nickels. The value equation is:
   \[
   P + 5N = 82
   \]

2. Her younger brother mistook all the nickels for dimes and counted the total as $1.47, which is 147 cents. The equation for his count is:
   \[
   P + 10N = 147
   \]

We now have the system of linear equations:
\[
\begin{cases}
P + 5N = 82 \\
P + 10N = 147
\end{cases}
\]

To eliminate \( P \), we subtract the first equation from the second:
\[
(P + 10N) - (P + 5N) = 147 - 82
\]
\[
5N = 65
\]
\[
N = 13
\]

Now that we have \( N = 13 \), we substitute this value back into the first equation to find \( P \):
\[
P + 5(13) = 82
\]
\[
P + 65 = 82
\]
\[
P = 17
\]

Thus, Jenifer has \(\boxed{17}\) pennies.<end_working_out><SOLUTION>17</SOLUTION><|endoftext|>

In [13]:
del dataset
torch.cuda.empty_cache()
import gc
gc.collect()

152

### Data Prep
<a name="Data"></a>

We're using Hugging Face's [Open R1 Math dataset](https://huggingface.co/datasets/open-r1/DAPO-Math-17k-Processed). You can also utilize OpenAI's famous [GSM8K dataset](https://huggingface.co/datasets/openai/gsm8k)

In [14]:
from datasets import load_dataset
dataset = load_dataset("open-r1/DAPO-Math-17k-Processed", "en", split = "train")
dataset

Dataset({
    features: ['prompt', 'solution', 'data_source', 'source_prompt', 'ability', 'reward_model', 'extra_info'],
    num_rows: 14116
})

In [15]:
dataset[0]["prompt"]

'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.'

In [16]:
dataset[0]["solution"]

'34'

In [17]:
def extract_hash_answer(text):
    # if "####" not in text: return None
    # return text.split("####")[1].strip()
    return text
extract_hash_answer(dataset[0]["solution"])

'34'

In [18]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["prompt"]},
    ],
    "answer": extract_hash_answer(x["solution"]),
})
dataset[0]

{'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION>',
   'role': 'system'},
  {'content': 'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.',
   'role': 'user'}],
 'solution': '34',
 'data_source': 'math_dapo',
 'source_prompt': [{'content': 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.\n\nIn triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.\n\nRemember to put your answer on its own line after "Answer:".',
   'role': 'user'}],
 'ability': 'MATH',
 'reward_model': {'ground_truth': '34', 'style': 'rule-lighteval/MATH_v2'},
 'extra_info': {'index': '9a9b6eb4-a1cb-49d1-8c1e-62eaf2f74079'},
 'answer': '34'}

In [19]:
import re

# Add optional EOS token matching
solution_end_regex = r"</SOLUTION>[\s]{0,}" + \
    "(?:" + re.escape(tokenizer.eos_token) + ")?"

match_format = re.compile(
    rf"{reasoning_end}.*?"\
    rf"{solution_start}(.+?){solution_end_regex}"\
    rf"[\s]{{0,}}$",
    flags = re.MULTILINE | re.DOTALL
)
match_format

re.compile(r'<end_working_out>.*?<SOLUTION>(.+?)</SOLUTION>[\s]{0,}(?:<\|endoftext\|>)?[\s]{0,}$',
           re.MULTILINE|re.DOTALL|re.UNICODE)

In [20]:
match_format.findall(
    "Let me think!<end_working_out>"\
    f"<SOLUTION>\n2\n</SOLUTION>",
)

['\n2\n']

In [21]:
match_format.findall(
    "<start_working_out>Let me think!<end_working_out>"\
    f"<SOLUTION>  2  </SOLUTION>\n\n",
)

['  2  ']

In [22]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

In [23]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Count how many keywords are seen - we penalize if too many!
        # If we see 1, then plus some points!

        # No need to reward <start_working_out> since we always prepend it!
        # score += 0.5 if response.count(reasoning_start) == 1 else -1.0
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 0.5 if response.count(solution_start)  == 1 else -1.0
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

In [24]:
def check_answer(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        # Correct answer gets 5 points!
        if guess == true_answer:
            score += 5.0
        # Match if spaces are seen, but less reward
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            # We also reward it if the answer is close via ratios!
            # Ie if the answer is within some range, reward it!
            try:
                ratio = float(guess) / float(true_answer)
                if   ratio >= 0.9 and ratio <= 1.1: score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2: score += 1.5
                else: score -= 2.5 # Penalize wrong answers
            except:
                score -= 4.5 # Penalize
        scores.append(score)
    return scores

In [25]:
match_numbers = re.compile(
    solution_start + r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)
print(match_numbers.findall("<SOLUTION>  0.34  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  123,456  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  -0.234  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>17</SOLUTION>"))

['0.34']
['123,456']
['-0.234']
['17']

In [26]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            true_answer = float(true_answer.strip())
            # Remove commas like in 123,456
            guess       = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess == true_answer else -1.5)
        except:
            scores.append(0)
            continue
    return scores

In [27]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

You are given a problem.
Think about the problem and provide your working out.
Place it between <start_working_out> and <end_working_out>.
Then, provide your solution between <SOLUTION></SOLUTION><|endoftext|>In triangle $ABC$, $\sin \angle A = \frac{4}{5}$ and $\angle A < 90^\circ$. Let $D$ be a point outside triangle $ABC$ such that $\angle BAD = \angle DAC$ and $\angle BDC = 90^\circ$. Suppose that $AD = 1$ and that $\frac{BD}{CD} = \frac{3}{2}$. If $AB + AC$ can be expressed in the form $\frac{a\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.<start_working_out>
Max Length =  201

In [28]:
max_prompt_length = maximum_length + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length

from vllm import SamplingParams
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    seed = 3407,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    vllm_sampling_params = vllm_sampling_params,
    temperature = 1.0,
    learning_rate = 5e-6,
    weight_decay = 0.001,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4, # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    num_train_epochs = 1, # Set to 1 for a full training run
    #max_steps = 100,
    save_steps = 100,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",

    #For optional training + evaluation
    fp16_full_eval = True,
    per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

Unsloth: We now expect `per_device_train_batch_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 4

In [ ]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
    ],
    args = training_args,
    train_dataset = dataset,

    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 12,709 | Num Epochs = 1 | Total steps = 12,709
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 66,060,288 of 4,088,528,384 (1.62% trained)

WARNING 12-16 22:04:40 [processor.py:228] vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.
********************Question:
Compute the number of positive integers that divide at least two of the integers in the set $\{1^1,2^2,3^3,4^4,5^5,6^6,7^7,8^8,9^9,10^{10}\}$.
Answer:
22
Response:
Okay, so I need to find how many positive integers divide at least two of the numbers in this set: {1^1, 2^2, 3^3, 4^4, 5^5, 6^6, 7^7, 8^8, 9^9, 10^10}. Hmm, let's start by figuring out what each of these numbers is. Let me compute them one by one.

1^1 is 1.
2^2 is 4.
3^3 is 27.
4^4 is 256.
5^5 is 3125.
6^6 is 46656.
7^7 is 823543.
8^8 is 16777216.
9^9 is 387420489.
10^10 is 10,000,000,000.

Okay, so that's all the numbers. Now, I need to find how many positive integers are divisors of at least two of these numbers. Hmm, maybe I can think of the set of all divisors and then see which ones appear in at least two of the numbers. But wait, some numbers might have common divisors. For example, if two numbers share a common factor, their greatest common divisor (GCD) will be their shared divisors. So maybe I should look for pairs of numbers and find their GCDs. Then, count the distinct divisors from those pairs.

But wait, but some numbers might have multiple pairs that share divisors. Like, maybe one number divides two others, and another number divides two others, and so on. So maybe I should consider all possible pairs? Let's see, how many pairs are there? There are 10 numbers, so the number of pairs is C(10,2) which is 45. But not all pairs will have a GCD greater than 1. So maybe I need to find all pairs where the GCD is greater than 1, then list all their divisors, and count the distinct ones?

Alternatively, maybe there's a smarter way. Let me think differently. The problem is asking for numbers that divide at least two elements in the set. So perhaps I can consider the prime factorizations of each number and see which primes are common to at least two numbers. Then the divisors would be all the combinations of those primes.

Let me list the prime factorizations of each number:

- 1^1: 1 (tricky. 1 has no prime factors)
- 2^2: 2^2
- 3^3: 3^3
- 4^4: (2^2)^4 = 2^8
- 5^5: 5^5
- 6^6: (2*3)^6 = 2^6 * 3^6
- 7^7: 7^7
- 8^8: (2^3)^8 = 2^24
- 9^9: (3^2)^9 = 3^18
- 10^10: (2*5)^10 = 2^10 * 5^10

Okay, so now, to find common divisors, we need to find primes that appear in the factorization of at least two numbers. Let's list the exponents for each prime in each number, since the GCD is determined by the minimum exponents of common primes.

Let's create a matrix where rows are the exponents of each prime in each number. Let's denote the numbers as N1 to N10 for simplicity.

Primes are 2, 3, 5, 7.

For each number, we'll list the exponents of 2, 3, 5, 7.

So:

N1 (1): 0, 0, 0, 0 (since 1 has no primes)

N2 (4): 2, 0, 0, 0

N3 (27): 0, 3, 0, 0

N4 (256): 8, 0, 0, 0

N5 (3125): 0, 0, 5, 0

N6 (46656): 6, 6, 0, 0

N7 (823543): 0, 0, 0, 7

N8 (16777216): 24, 0, 0, 0

N9 (387420489): 0, 18, 0, 0

N10 (10000000000): 10, 0, 10, 0

Now, to find common divisors, we need to find primes where there are at least two numbers with that prime in their factorization. So for each prime, count how many numbers have that prime in their factorization. If the count is at least 2, then that prime is contributing to common divisors.

Let's check for each prime:

Prime 2: appears in N2, N4, N6, N8, N10. That's 5 numbers. So yes, contributes.

Prime 3: appears in N3, N6, N9. That's 3 numbers. Yess.

Prime 5: appears in N5, N10. That's 2 numbers. Yes.

Prime 7: appears in N7. That's only one number. Doesn't contribute.

So the primes that contribute to common divisors are 2, 3, 5. So any divisor of the form 2^a * 3^b * 5^c where a, b, c >=0 and each is within the minimum exponents in the shared numbers.

So for each prime, the possible exponents in the divisors range from 0 to the minimum across the numbers that have that prime.

Let's find the minimum for each prime across the contributing numbers.

Prime 2: min exponents are in N2 (0), N4 (0), N6 (0), N8 (0), N10 (0). Wait, all these have exponent 0 except N2, N4, N6, N8 have higher exponents. But since some have 0, the minimum is 0. So for 2, exponents can be 0 to min (which is 0), so exponent 0. So for 2, possible exponents: 0.

Wait, but if a prime is not in some of the numbers, then the minimum would be 0. So if the minimum for a prime across the numbers is m, then the possible exponents are from 0 to m.

But since 2 is in N2 (2), N4 (8), N6 (6), N8 (24), N10 (10). The minimum there is 0. Oops, that's incorrect. Wait, all of them have exponent 0 for 2? Wait, hold on. Let me check again.

Looking at N2: exponent 2. N4: 8. N6: 6. N8: 24. N10: 10. So all numbers except N1 and N3 have at least exponent 1 for prime 2. So the minimum exponent for 2 across the contributing numbers is 1.

So for 2, possible exponents in the divisors are from 0 to 1. So 2^0, 2^1.

Similarly, for prime 3: It's in N3 (3), N6 (6), N9 (18). The minimum exponent is 3. So 3^3, 3^4, ..., 3^18. But wait, the problem is asking for divisors that are common to at least two numbers. So for 3, the minimum across the numbers that have 3 is 3. So divisors can have 3^3, 3^4, ..., 3^18.

Wait, but actually, for each prime, the exponents in the divisors can go up to the minimum exponent in the two numbers that divide each other. So for two numbers both having 3^3, then the divisors can have 3^0, 3^1, ..., 3^3. Because the GCD would limit the
Extracted:
None

********************Question:
The sum of $\lfloor x \rfloor$ for all real numbers $x$ satisfying the equation $16 + 15x + 15x^2 = \lfloor x \rfloor^3$ is:
Answer:
33
Response:
Okay, so I need to solve the equation 16 +15x +15x² = floor(x)³ and then find the sum of the floor of x for all real solutions. Hmm, let's see. The floor function, denoted by ⌊x⌋, gives the greatest integer less than or equal to x. So, when dealing with this equation, I think I need to consider that ⌊x⌋ is an integer, and then find the corresponding x that satisfies the equation.

Let me denote ⌊x⌋ as n, where n is an integer. Then the equation becomes 16 +15x +15x² = n³. But since n ≤ x < n+1, I can use this inequality to find possible values of n. Maybe I can rearrange the equation to solve for x in terms of n, like a quadratic equation. Let's write the equation as 15x² +15x +16 - n³ = 0. If I treat this as a quadratic in x, the solutions will be real only if the discriminant is non-negative. Let me compute the discriminant first.

The discriminant D of ax² + bx + c is b² -4ac. Here, a=15, b=15, c=16-n³. So D = 15² -4*15*(16 -n³) = 225 -60(16 -n³) = 225 -960 +60n³ = 60n³ -735. For real solutions, D ≥ 0, so 60n³ -735 ≥0. Let's solve for n: n³ ≥ 735/60 =12.25. Since n is an integer, n³ ≥13, so n ≥2. Because 2³ =8 <13 and 3³=27≥13. So possible integer values for n starting from 2 upwards. But wait, I should check if these values of n actually give solutions x such that n ≤ x < n+1.

Let me test n=2. Then the equation becomes 15x² +15x +16 -8 =0 or 15x² +15x +8 =0. The discriminant is 225 -480 = -255, which is negative. So no real solutions here. So n=2 doesn't work.

Next, n=3: equation 15x² +15x +16 -27=0 → 15x² +15x -11=0. Discriminant is 225 +660=885. Positive, so two real solutions. Let's compute x. Using the quadratic formula: x = [-15 ±√885]/30. So x ≈ [-15 ±29.75]/30. The possible solutions are x ≈ (14.75)/30 ≈0.492 and x ≈ (-44.75)/30 ≈-1.492. But since n=3 implies 3≤x<4, only x≈0.492 is in this interval. But wait, floor of x is 3, but x is approximately 0.492, which is less than 3. That's a contradiction. So n=3 doesn't work either.

Next, n=4: equation 15x² +15x +16-64=0 → 15x² +15x -48=0. Dividing by 3: 5x² +5x -16=0. Discriminant is 25 +320=345. Positive, so two real solutions. x = [-5±√345]/10. √345 ≈18.575, so x ≈ (13.575)/10 ≈1.357 and x ≈ (-23.575)/10≈-2.358. But for n=4, we need 4≤x<5. The first solution is approximately 1.357, which is less than 4, so not valid. The second solution is negative, which is also not in the desired range. So no solutions here either.

n=5: equation 15x² +15x +16-125=0 → 15x² +15x -109=0. Discriminant is 225+6360=6585. Positive. Solutions are x = [-15±√6585]/30. √6585 is around 81.15, so x ≈ (66.15)/30 ≈2.205 and x ≈ (-96.15)/30≈-3.205. For n=5, we need 5≤x<6. The first solution is approximately 2.205, which is less than 5. The second solution is negative and thus invalid. So no solutions here.

n=6: equation 15x² +15x +16-216=0 → 15x² +15x -200=0. Divide by 5: 3x² +3x -40=0. Discriminant is 9 +480=489. Positive. Solutions are x = [-3±√489]/6. √489 ≈22.113, so x ≈ (19.113)/6≈3.186 and x≈ (-25.113)/6≈-4.186. For n=6, need 6≤x<7. The first solution is approximately 3.186, which is less than 6. The second solution is negative. So no solutions here.

n=7: equation 15x² +15x +16-343=0 → 15x² +15x -327=0. Divide by 3: 5x² +5x -109=0. Discriminant is 25 +2180=2205. Positive. Solutions are x = [-5±√2205]/10. √2205 ≈46.96, so x ≈ (41.96)/10≈4.196 and x≈ (-51.96)/10≈-5.196. For n=7, need 7≤x<8. The first solution is approximately 4.196, which is less than 7. So no solutions.

n=8: equation 15x² +15x +16-512=0 → 15x² +15x -496=0. Divide by 3: 5x² +5x -165.333... Let me compute that. So 15/3=5, 15/3=5, 16*3=48, 512-48=504, so 504/3=168. Wait, no. Let me divide the whole equation by 5. So 3x² +3x -165.333... Wait, wait. 16*3=48, 512-48=504, 504/3=168. But 496 divided by 3 is approximately 165.333. Wait, 3x² +3x -165.333... So dividing by 3 gives x² +x -55.088... Wait, but since we can't have fractions, maybe better to keep it as 15x² +15x -496=0. Let me use the quadratic formula: x = [-15±√(225 +66240)]/30 = [-15±√66465]/30. √66465 is approximately 257.8. So x ≈ (1
Extracted:
None
********************Question:
Letters $A, B, C,$ and $D$ represent four different digits from 0, 1, 2, 3, ..., 9. If $\frac{A+B}{C+D}$ is an integer that is as large as possible, what is the value of $A+B$?
Answer:
17
Response:
Okay, so I need to figure out four different digits A, B, C, D from 0 to 9 such that the fraction (A + B) / (C + D) is an integer and as large as possible. Then, I need to find what A + B equals. Hmm, let me break this down.

First, since we're dealing with digits, each of A, B, C, D is between 0 and 9, but they all have to be different. Also, the fraction (A+B)/(C+D) needs to be an integer. That means C+D has to divide evenly into A+B. And we want this integer to be as large as possible. So, to maximize the integer, we need A+B to be as large as possible and C+D to be as small as possible, right? Because the larger the numerator and the smaller the denominator, the bigger the fraction can be if it's an integer.

Let me think. The largest possible A+B would be 18, since the maximum digits are 9 and 8. But then C+D would have to be a divisor of 18. The divisors of 18 are 1, 2, 3, 6, 9, 18. But since C and D are different digits and their sum must be one of these divisors, the smallest possible C+D is 1. So if C+D is 1, then A+B is 18, which is the maximum possible. But wait, can C+D be 1? The smallest possible sum of two different digits is 0+1=1. So yes, that's possible. So then A and B would have to be 9 and 8 (since they need to be different from C and D). So A+B would be 17+1=18. But wait, let me check if there's a possibility where the integer is larger than 18. If C+D can be smaller than 1, but the smallest sum of two different digits is 1. So yeah, the maximum integer is 18. So A+B would be 18 in that case. But wait, the problem says the fraction is "as large as possible." Since 18/1 is bigger than any other integer value we could get by making C+D larger, so that's the maximum. Therefore, A+B is 18. But let me make sure I'm not missing any other combinations.

What if C+D is 2? Then A+B would need to be 2, 4, 6, 9, or 18. But to maximize the integer, we'd choose the largest possible A+B, which is 18. So that would give an integer of 9. That's larger than 18/1=18. Wait, no. Let me compare: 18/1 vs 18/2. 18/1 is 18, 18/2 is 9. So 18/1 is larger. So no, C+D can't be 2. Because then the integer is smaller. Similarly, if C+D is 3, then A+B must be a multiple of 3, so 9, 12, 15, 18. The maximum is 18, which gives 6. Again, 18/1 is larger. So even if we increase C+D, the integer gets smaller. Therefore, the maximum integer is achieved when C+D is 1. Therefore, A+B is 18.

But wait, does this actually violate any constraints? Like, can the digits all be different? If C+D is 1, the possible pairs are (0,1) and (1,0). So C and D could be 0 and 1. Then A and B must be different from 0 and 1, and also different from each other. The maximum A+B would be 8+9=17, but wait, that's less than 18. So how is that possible? Oh, if A and B are 8 and 9, then C and D are 0 and 1. That's all different digits. So 8+9=17 is possible, but that gives the integer 17/1=17, which is smaller than 18. So yes, A+B can be 18. So the maximum is achieved when C+D is 1. Therefore, A+B is 18. So the answer should be 18.
To maximize the integer value of \(\frac{A+B}{C+D}\), we need to ensure that \(A+B\) is as large as possible and \(C+D\) is as small as possible. The largest possible sum for \(A+B\) using different digits is 17 (when \(A=9\) and \(B=8\)), because the digits must be distinct and range from 0 to 9. However, we need to check if there is a larger possible value by considering other combinations.

The smallest possible sum for \(C+D\) using different digits is 1, which can be achieved with the digits 0 and 1. Therefore, if \(C+D = 1\), then \(A+B\) must be 17 times a multiple of 1, which simplifies to 17. However, we can also consider other possible values for \(C+D\) to see if we can achieve a larger integer.

If \(C+D = 2\), then \(A+B\) must be a multiple of 2, such as 2, 4, 6, 8, 10, 12, 14, 16, or 18. The largest possible value for \(A+B\) in this case is 18, but we need to check if this combination is feasible with distinct digits. For \(A+B = 18\), the digits could be 9 and 8, and \(C+D\) would be 2, with possible pairs (0,2), (1,1), (2,0). However, (1,1) is not allowed because the digits must be distinct. So, the valid pairs are (0,2) and (2,0), both of which are possible. This gives us \(\frac{18}{2} = 9\), which is smaller than 18.

If \(C+D = 3\), then \(A+B\) must be a multiple of 3, such as 6, 9, 12, 15, or 18. The largest possible value for \(A+B\) is 18, giving \(\frac{18}{3} = 6\), which is smaller than 9.

If \(C+D = 4\), then \(A+B\) must be a multiple of 4, such as 8, 12, or 16. The largest possible value for \(A+B\) is 16, giving \(\frac{16}{4} = 4\), which is smaller than 9.

If \(C+D = 5\), then \(A+B\) must be a multiple of 5, such as 10 or 15. The largest possible value for \(A+B\) is 15, giving \(\frac{15}{5} = 3\), which is smaller than 9.

If \(C+D = 6\), then \(A+B\) must be a multiple of 6, such as 12 or 18. The largest possible value for \(A+B\) is 18, giving \(\frac{18}{6} = 3\), which is smaller than 9.

If \(C+D = 7\), then \(A+B\) must be a multiple of 7, such as 14. The largest possible value for \(A+B\) is 14, giving \(\frac{14}{7} = 2\), which is smaller than 9.

If \(C+D = 8\), then \(A+B\) must be a multiple of 8, such as 16. The largest possible value for \(A+B\) is 16, giving \(\frac{16}{8} = 2\), which is smaller than 9.

If \(C+D = 9\), then \(A+B\) must be a multiple of 9, such as 18. The largest possible value for \(A+B\) is 18, giving
Extracted:
None
********************Question:
Let $f(x)=\int_0^{x} e^{t} (\cos t+\sin t)\, dt$, $g(x)=\int_0^{x} e^{t} (\cos t-\sin t)\, dt$.

For a real number $a$, find:
\[ \sum_{n=1}^{\infty} \frac{e^{2a}}{\{f^{(n)}(a)\}^2+\{g^{(n)}(a)\}^2}. \]
Answer:
1
Response:
Okay, so I need to find the sum from n=1 to infinity of e^(2a) divided by the sum of the squares of the nth derivatives of f at a and g at a. Hmm, let me start by trying to understand the functions f and g. They're both integrals from 0 to x of exponential times trigonometric functions. Maybe I should compute the first and second derivatives to see if there's a pattern here.

Let me recall that when taking derivatives of integrals of the form ∫ from 0 to x of some function, the fundamental theorem of calculus says the derivative swaps the variable of integration with the limit. So, the derivative of f(x) with respect to x should be e^x(cos x + sin x), right? Because the upper limit is x, and the integrand evaluated at x is e^x (cos x + sin x). Similarly, the derivative of g(x) should be e^x (cos x - sin x). Let me check that.

For f(x), the integrand is e^t (cos t + sin t). So, f'(x) = e^x (cos x + sin x). Yep, that makes sense. Then, the second derivative would be differentiating that again. Let me compute f''(x). Differentiating e^x (cos x + sin x), using the product rule: (e^x)'(cos x + sin x) + e^x (d/dx)(cos x + sin x). So, that's e^x (cos x + sin x) + e^x (-sin x + cos x) = e^x (cos x + sin x - sin x + cos x) = e^x (2 cos x) = 2 e^x cos x.

Similarly, for g(x), g'(x) = e^x (cos x - sin x). Then, g''(x) would be e^x (cos x - sin x) + e^x (-sin x - cos x) = e^x (cos x - sin x - sin x - cos x) = e^x (-2 sin x) = -2 e^x sin x. Interesting, so the second derivatives involve sin and cos terms multiplied by -2 and 2 respectively.

Wait, when taking higher derivatives, maybe there's a pattern? Let me compute the third derivatives. f'''(x) would be the derivative of 2 e^x cos x, which is 2e^x cos x + 2e^x (-sin x) = 2e^x (cos x - sin x). But that's the same as f'(x) times 2. Wait no, f'(x) is e^x (cos x + sin x). Hmm, maybe the derivatives cycle every two steps? Let me find a pattern.

Alternatively, maybe instead of computing each derivative, I can express the nth derivative in terms of previous ones. For example, if I can find a recurrence relation, that might help. Let me think.

For f(x), starting from the first derivative: f'(x) = e^x (cos x + sin x). Let's denote this as f_0(x). Then, f_1(x) = f_0'(x) = 2 e^x cos x. Next, f_2(x) = f_1'(x) = 2 e^x cos x + 2 e^x (-sin x) = 2 e^x (cos x - sin x). Wait, but let me check f_3(x) = f_2'(x) = 2 e^x (cos x - sin x) + 2 e^x (-sin x - cos x) = 2 e^x (cos x - sin x - sin x - cos x) = 2 e^x (-2 sin x) = -4 e^x sin x. So, the coefficients are doubling each time: 1, 2, 4, 8, ...

Similarly, for g(x), starting with g'(x) = e^x (cos x - sin x), denoted g_0(x). Then, g_1(x) = g_0'(x) = -2 e^x sin x. Next, g_2(x) = g_1'(x) = -2 e^x sin x + (-2 e^x cos x) = -2 e^x (sin x + cos x). Then, g_3(x) = g_2'(x) = -2 e^x (sin x + cos x) + (-2 e^x (cos x - sin x)) = -2 e^x (sin x + cos x + cos x - sin x) = -2 e^x (2 cos x) = -4 e^x cos x. The coefficients here are also doubling: -1, -2, -4, -8, ...

So, for f_n(x), the coefficient seems to be 2^n, alternating with sin and cos. Similarly, for g_n(x), the coefficient is 2^n, alternating with sin and cos but in the opposite order.

Wait, let me confirm with the pattern. For f_n(x):

n=0: e^x (cos x + sin x) -> coefficient 1 for cos, 1 for sin
n=1: 2 e^x cos x -> coefficient 2 for cos
n=2: 2 e^x (cos x - sin x) -> coefficient 2 for cos, -2 for sin
n=3: -4 e^x sin x -> coefficient -4 for sin
n=4: -4 e^x (cos x + sin x) -> coefficient -4 for cos, -4 for sin
n=5: 8 e^x cos x -> coefficient 8 for cos
... and so on. Similarly for g_n(x), it's the opposite sequence of signs for the coefficients.

But the problem asks for the sum of the ratios of e^(2a) over the sum of the squares of the nth derivatives evaluated at a. So, the general term in the series is e^(2a) / (f_n^(n)(a)^2 + g_n^(n)(a)^2). Given the patterns above, maybe the derivatives at a simplify nicely.

Wait, but the derivatives are exponential times trigonometric functions evaluated at a. So, f_n^(n)(a) = (coeff a) * e^a * cos a or sin a, depending on the parity of n. Let me see:

For f(x), the coefficients alternate between 2^n times cos (if n is even minus, n is odd plus) but wait let me check. In even n, the coefficient is 2^n multiplied by the cosine, in odd n by the sine. For example, at a, f_n^(n)(a) is 2^n e^a cos a if n is even, 2^n e^a sin a if n is odd. Similarly, for g_n^(n)(a), it's the same coefficients but for the different trig function. So for even n, g_n^(n)(a) = 2^n e^a cos a, and for odd n, g_n^(n)(a) = 2^n e^a -sin a.

Therefore, f_n^(n)(a)^2 = (2^n e^a)^2 (cos^2 a) if n even, or (2^n e^a)^2 (sin^2 a) if n odd. Similarly, g_n^(n)(a)^2. So, when n is even, f_n^(n)(a)^2 = 2^(2n) e^(2a) cos²a, g_n^(n)(a)^2 = 2^(2n) e^(2a) cos²a. So their sum is 2 * 2^(2n) e^(2a) cos²a. Therefore, the term is e^(2a) / (2 * 2^(2n) e^(2a) cos²a) = 1 / (2 * 2^(2n) cos²a) = 1 / (2^(2n +1) cos²a).

When n is odd, f_n^(n)(a)^2 = 2^(2n) e^(2a) sin²a, g_n^(n)(a)^2 = 2^(2n) e^(2a) (-sin a)^2 = 2^(2n) e^(2a) sin²a. So sum is 2 * 2^(2n) e^(2a) sin²a. So the term is e^(
Extracted:
None
********************Question:
How many distinct ordered pairs of positive integers $(m,n)$ are there so that the sum of the reciprocals of $m$ and $n$ is $\frac14$?
Answer:
5
Response:
Okay, let's try to figure out how many distinct ordered pairs of positive integers (m, n) satisfy the equation 1/m + 1/n = 1/4. Hmm, starting with the equation, maybe I should rewrite it to make it easier to work with. If I combine the fractions on the left side, I get (m + n)/(mn) = 1/4. So cross-multiplying that gives 4(m + n) = mn. Let me rearrange that equation: moving all terms to one side gives mn - 4m - 4n = 0. Now, I remember in algebra when you have an expression like this, sometimes adding a number that lets you factor it is helpful. Maybe I can complete the rectangle or something? Let me try adding 16 to both sides. Why 16? Because (4m)(4n) = 16mn, but since the coefficient of mn is 1, adding 16 would help in factoring. Wait, no. Let me do it right. Let's rewrite the equation as mn - 4m - 4n = 0. If I add 16 to both sides now, that would make it mn - 4m - 4n +16 = 16. Now that can be factored as (m -4)(n -4) = 16. Wow, that's a clever trick! So now the problem reduces to finding all pairs of integers (m-4, n-4) that multiply to 16. Since m and n are positive integers, m-4 and n-4 must also be positive integers (because subtracting 4 from a positive integer gives a non-negative integer, but since they're in the denominator originally, they can't be zero). So we need to find all positive integer factor pairs of 16. The factor pairs of 16 are (1,16), (2,8), (4,4), (8,2), and (16,1). Each of these pairs corresponds to a solution (m,n) when you add 4 back. So for each pair (a,b), the solution would be (a+4, b+4). Therefore, each factor pair gives a distinct ordered pair (m,n). Let me list them out:

1. (1,16) → (5,20)
2. (2,8) → (6,12)
3. (4,4) → (8,8)
4. (8,2) → (12,6)
5. (16,1) → (20,5)

Now let me check if all these pairs are distinct. Looking at the first few: (5,20) and (20,5) are different, (6,12) and (12,6) are different, and (8,8) is its own pair. So each of these pairs gives a distinct ordered pair. Since there are 5 factor pairs, there should be 5 solutions. Wait, but let me make sure that all these pairs satisfy the original equation. For example, take (5,20): 1/5 + 1/20 = (4+1)/20 = 5/20 = 1/4. Yep, that works. Let's check another one, like (12,6): 1/12 + 1/6 = 1/12 + 2/12 = 3/12 = 1/4. That also works. And (8,8): 1/8 + 1/8 = 2/8 = 1/4. All these pairs check out. So the number of distinct ordered pairs should be equal to the number of factor pairs of 16. The positive integer factor pairs of 16 are 5 pairs, so the answer should be 5. Wait, but hold on, wait. Let me think again. The factors of 16 are 1,2,4,8,16. The pairs are (1,16), (2,8), (4,4), (8,2), (16,1). Each of these gives a different (m,n). So yeah, there are 5 pairs. But wait, maybe I didn't count correctly. Let me verify again: 16 factors: 1,2,4,8,16. Pairs are (1,16), (2,8), (4,4), then reverse pairs like (8,2) and (16,1). So that's 5 pairs. Therefore, there should be 5 solutions. So the answer should be 5. Let me make sure there isn't a trick here. The problem is that when dealing with reciprocals, sometimes you might think there are more solutions, but since m and n are positive integers, and their reciprocals sum to 1/4, the only way is through these factor pairs. So yeah, the answer should be 5. I think that's right. Alright, the answer is 5.
To solve the problem of finding how many distinct ordered pairs of positive integers \((m, n)\) satisfy the equation \(\frac{1}{m} + \frac{1}{n} = \frac{1}{4}\), we start by rewriting the equation in a more manageable form.

First, we combine the fractions on the left-hand side:
\[
\frac{1}{m} + \frac{1}{n} = \frac{m + n}{mn} = \frac{1}{4}.
\]

Next, we cross-multiply to eliminate the fractions:
\[
4(m + n) = mn.
\]

Rearranging the equation, we get:
\[
mn - 4m - 4n = 0.
\]

To factor this equation, we add 16 to both sides:
\[
mn - 4m - 4n + 16 = 16.
\]

This can be factored as:
\[
(m - 4)(n - 4) = 16.
\]

Now, we need to find all pairs of positive integers \((a, b)\) such that \(a \cdot b = 16\). The factor pairs of 16 are:
\[
(1, 16), (2, 8), (4, 4), (8, 2), (16, 1).
\]

Each pair \((a, b)\) corresponds to a solution \((m, n)\) where \(m = a + 4\) and \(n = b + 4\). Therefore, the solutions are:
\[
(1+4, 16+4) = (5, 20), \quad (2+4, 8+4) = (6, 12), \quad (4+4, 4+4) = (8, 8), \quad (8+4, 2+4) = (12, 6), \quad (16+4, 1+4) = (20, 5).
\]

These pairs are all distinct and satisfy the original equation. Counting these pairs, we find there are 5 distinct ordered pairs.
